import sys

Import('env')

baghash_env = env.Clone()

test_srcs = [
    "mutest.c",
    "bitstream_test.c",
    "compress_test.c",
    "hash_state_test.c",
    "options_test.c"
]

libs = [
  "baghash",
  "crypto"
]

# Run the mutest script to generate the test harness code
bld = Builder(action = 'bagtest/mkmutest bagtest/mutest.h $SOURCES | $CC -c -xc -o $TARGET -')
baghash_env.Append(BUILDERS = {'MkMutest' : bld})

baghash_env.Append(LIBS = libs)

# Copy the mutest scripts to the build dir
baghash_env.Install("mkmutest")
baghash_env.Install("mutest.h")

test_objs = baghash_env.Object(test_srcs)
test_main = baghash_env.MkMutest(test_objs)
baghash_env.Program("bagtest", [test_main] + test_objs)

