/*
 * Copyright (c) 2015, Henry Corrigan-Gibbs
 * 
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef __ERRORS_H__
#define __ERRORS_H__

enum error_codes {
  ERROR_NONE,

  ERROR_INCOMPATIBLE_OPTIONS,

  ERROR_NULL_POINTER,
  ERROR_MALLOC,

  ERROR_MCOST_TOO_BIG,
  ERROR_TCOST_TOO_BIG,

  ERROR_OUTLEN_TOO_SMALL,
  ERROR_OUTLEN_TOO_BIG,

  ERROR_INLEN_TOO_BIG,
  ERROR_SALTLEN_TOO_BIG,

  ERROR_NTHREADS_TOO_BIG,

  ERROR_CANNOT_EXTRACT_BEFORE_MIX,

  ERROR_OPENSSL_HASH,
  ERROR_OPENSSL_AES,

  ERROR_BITSTREAM_UNINITIALIZED,
  ERROR_BITSTREAM_FINALIZED,
  ERROR_BITSTREAM_MAX_TOO_SMALL,

  ERROR_PTHREAD

};

#endif
