import os

Import('env')

src = [
    "api.c",
    "balloon.c",
    "base64.c",
    "bitstream.c",
    "compress.c",
    "encode.c",
    "errors.c",
    "hash_state.c",
    "parse.c",
]

libs = [
  "-lpthread"
]

env.Append(LIBS = libs)
env.StaticLibrary("balloon", src)

