import os

Import('env')

src = [
    "balloon.c",
    "bitstream.c",
    "compress.c",
    "hash_state.c",
    "hash_state_argon2.c",
    "hash_state_double.c",
    "hash_state_double_par.c",
    "hash_state_double_pipe.c",
    "hash_state_scrypt.c",
    "hash_state_single.c",
    "options.c",
    "xor.c"
]

libs = [
  "blake2b",
  "echo",
  "keccak",
  "sempira",
]

env.Append(LIBS = libs)
env.StaticLibrary("balloon", src)

