import os

Import('env')

src = [
    "balloon.c",
    "bitstream.c",
    "compress.c",
    "hash_state.c",
    "options.c",
    "xor.c"
]

libs = [
  "keccak",
]

env.Append(LIBS = libs)
env.StaticLibrary("balloon", src)

