import sys

Import('env')

balloon_env = env.Clone()

src = [
    "main.c",
]

libs = [
  "balloon",
]

conf = Configure(env)
if conf.CheckCHeader('papi.h'):
    balloon_env.Append(CFLAGS = '-DHAS_PAPI_H')
    libs.append("papi")

balloon_env.Append(LIBS = libs)
balloon_env.Program("bench", src)

