import sys

Import('env')

ballon_env = env.Clone()

src = [
    "main.c",
]

libs = [
  "balloon",
]

conf = Configure(env)
if conf.CheckCHeader('papi.h'):
    conf.env.Append('-DHAS_PAPI_H')
    libs.append("papi")

ballon_env.Append(LIBS = libs)
ballon_env.Program("bench", src)

