import sys

Import('env')

baghash_env = env.Clone()

src = [
  "matrix_gen.cpp"
]

libs = [
]

baghash_env.Append(CPPDEFINES = ["Boost_USE_STATIC_LIBS"])
baghash_env.Append(LIBS = libs)
baghash_env.StaticLibrary("matgen", src)

