import os
import sys

Import('env')

src = []

# The ECHO assemly code does not compile on Mac OS X without
# headaches, so we will just use the C code on Mac.
if sys.platform == 'darwin':
  src.append("echo64.c")
else:
  src.append("echo64.s")

env.Append(CFLAGS = ["-Wno-error=strict-aliasing"])
env.StaticLibrary("echo", src)

