import os

Import('env')

src = [
    "baghash.c",
    "bitstream.c",
    "compress.c",
    "hash_state.c",
    "hash_state_argon2.c",
    "hash_state_double.c",
    "hash_state_double_par.c",
    "hash_state_single.c",
    "options.c",
    "xor.c"
]

libs = [
  "blake2b",
  "echo",
  "keccak",
]

env.Append(LIBS = libs)
env.StaticLibrary("baghash", src)

