import os

Import('env')

src = [
    "baghash.c",
    "bitstream.c",
    "compress.c",
    "hash_state.c",
    "util.c",
]

libs = [
  "libkeccak",
]

env.Append(LIBS = libs)
env.StaticLibrary("baghash", src)

